apiVersion: redhatcop.redhat.io/v1alpha1
kind: NamespaceConfig
metadata:
  name: infra-secret-access
spec:
  labelSelector:
    matchLabels:
      infra-secrets: "true"       
  templates:                       
    - objectTemplate: |
        kind: ClusterRoleBinding
        apiVersion: rbac.authorization.k8s.io/v1
        metadata:
          name: {{ .Name }}-vault-access
        subjects:
          - kind: ServiceAccount
            name: default
            namespace: {{ .Name }}
        roleRef:
          kind: ClusterRole
          name: system:auth-delegator
          apiGroup: rbac.authorization.k8s.io
      excludedPaths:	
        - .spec.replicas	
        - .metadata	
        - .status