apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: ocp-local-cluster 
  namespace: sso
  labels:
    app: sso
spec:
  realmSelector:
    matchLabels:
      app: sso
  client:
    id: ocp-hub-client
    clientId: ocp-hub-client
    secret: ocp-secret
    rootUrl: https://oauth-openshift.apps.${CLUSTER_BASE_DOMAIN}/oauth2callback
    redirectUris:
      - /oidckeycloak
    clientAuthenticatorType: client-secret
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    implicitFlowEnabled: false
    defaultClientScopes:
      - profile
      - email
    consentRequired: false
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: backstage
  namespace: sso
  labels:
    app: sso
spec:
  realmSelector:
    matchLabels:
      app: sso
  client:
    id: backstage
    clientId: backstage
    secret: ocp-secret
    rootUrl: https://backstage-developer-hub-rhdh.apps.${CLUSTER_BASE_DOMAIN}
    redirectUris:
      - /api/auth/oidc/handler/frame
    clientAuthenticatorType: client-secret
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    implicitFlowEnabled: false
    defaultClientScopes:
      - profile
      - email
      - roles
    consentRequired: false
    serviceAccountsEnabled: true
    publicClient: false
  serviceAccountClientRoles:
    realm-management:
      - query-groups
      - query-users
      - view-users
  serviceAccountRealmRoles:
    - default-roles-myorg         
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: vault
  namespace: sso
  labels:
    app: sso
spec:
  realmSelector:
    matchLabels:
      app: sso
  client:
    id: vault
    clientId: vault
    secret: vault-secret
    redirectUris:
      - https://vault.apps.${CLUSTER_BASE_DOMAIN}/ui/vault/auth/keycloak/oidc/callback
      - https://vault.apps.${CLUSTER_BASE_DOMAIN}/v1/auth/keycloak/oidc/callback
      - http://localhost:8250/oidc/callback
    clientAuthenticatorType: client-secret
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    implicitFlowEnabled: false
    defaultClientScopes:
      - profile
      - email
    consentRequired: false
    protocolMappers:
    - config:
        claim.name: aud
        claim.value: vault
        id.token.claim: "true"
        access.token.claim: "true"
        userinfo.token.claim: "true"
      name: vault
      protocol: openid-connect
      protocolMapper: oidc-hardcoded-claim-mapper
    - name: groups
      protocol: openid-connect
      protocolMapper: "oidc-group-membership-mapper"
      config:
        "access.token.claim": "true"
        "claim.name": "groups"
        "full.path": "false"
        "id.token.claim": "true"
        "userinfo.token.claim": "true"
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: argocd
  namespace: sso
  labels:
    app: sso
spec:
  realmSelector:
    matchLabels:
      app: sso
  client:
    id: argocd-client
    clientId: argocd-client
    secret: ocp-secret
    redirectUris:
      - https://tenant-gitops-server-tenant-gitops.apps.${CLUSTER_BASE_DOMAIN}/auth/callback/*
    clientAuthenticatorType: client-secret
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    implicitFlowEnabled: false
    defaultClientScopes:
      - profile
      - email
    consentRequired: false
    protocolMappers:
    - name: groups
      protocol: openid-connect
      protocolMapper: "oidc-group-membership-mapper"
      config:
        "access.token.claim": "true"
        "claim.name": "groups"
        "full.path": "false"
        "id.token.claim": "true"
        "userinfo.token.claim": "true"  
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: gitlab
  namespace: sso
  labels:
    app: sso
spec:
  realmSelector:
    matchLabels:
      app: sso
  client:
    id: gitlab-client
    clientId: gitlab-client
    secret: ocp-secret
    redirectUris:
      - https://gitlab.apps.${CLUSTER_BASE_DOMAIN}/users/auth/openid_connect/callback
    clientAuthenticatorType: client-secret
    standardFlowEnabled: true
    directAccessGrantsEnabled: true
    implicitFlowEnabled: false
    defaultClientScopes:
      - profile
      - email
    consentRequired: false
    protocolMappers:
    - name: groups
      protocol: openid-connect
      protocolMapper: "oidc-group-membership-mapper"
      config:
        "access.token.claim": "true"
        "claim.name": "groups"
        "full.path": "false"
        "id.token.claim": "true"
        "userinfo.token.claim": "true"
  serviceAccountClientRoles:
    realm-management:
      - query-groups
      - query-users
      - view-users                          
      

              