applications:

  crossplane-providers:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: crossplane-system
    source:
      path: components/crossplane-providers

  namespace-configurations:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '15'
    destination:
      namespace: namespace-configuration-operator
    source:
      path: groups/multi-tenant/overlays/namespace-configurations

  openshift-config:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: openshift-config  
    source:
      path: components/openshift-config

  vault-admin:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '6'
    destination:
      namespace: vault-admin  
    source:
      path: groups/multi-tenant/overlays/vault-admin      

  approved-namespaces-app:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '25'
    destination:
      namespace: default
    source:
      path: components/approved-namespaces-app      

  vault-sidecar-injection:
    annotations:
      argocd.argoproj.io/compare-options: IgnoreExtraneous
      argocd.argoproj.io/sync-wave: '5'
    destination:
      namespace: vault
    source:
      path: groups/multi-tenant/overlays/vault-sidecar-injection                     


     