apiVersion: redhatcop.redhat.io/v1alpha1
kind: KubernetesAuthEngineRole
metadata:
  name: crossplane
  namespace: vault-admin
spec:
  authentication: 
    path: ${CLUSTER_NAME}
    role: vault-admin
  path: ${CLUSTER_NAME}
  policies:
    - crossplane-secrets-${CLUSTER_NAME}
  targetNamespaces:
    targetNamespaceSelector:
      matchLabels:
        crossplane-secrets: ""
  targetServiceAccounts:
  - "*"