apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace:  redhat-developer-hub

resources:
- ./namespace.yaml
- ./keycloak-client-secret-backstage.yaml
- ./patches-rbac.yaml
- ./patches.yaml
# - ./postgresql-creds-secret.yaml
- ./link.yaml

# helmGlobals:
#   chartHome: ../../../../.helm/charts

helmCharts:
  - name: redhat-developer-hub
    repo: https://charts.openshift.io
    releaseName: redhat-developer-hub
    version: 1.1.2
    namespace: redhat-developer-hub
    valuesFile: values.yaml
  # - name: developer-hub
  #   releaseName: redhat-developer-hub
  #   namespace: redhat-developer-hub
  #   valuesFile: values.yaml  
