apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-install-config
type: Opaque
stringData:
  install-config.yaml: |-
    apiVersion: v1
    metadata:
      name: '{{ .Release.Name }}'
    baseDomain: ${PLATFORM_BASE_DOMAIN}
    controlPlane:
      architecture: amd64
      hyperthreading: Enabled
      name: master
      replicas: 3
      platform:
        aws:
          rootVolume:
            iops: 4000
            size: 100
            type: io1
          type: m5.xlarge
    compute:
    - hyperthreading: Enabled
      architecture: amd64
      name: 'worker'
      replicas: 3
      platform:
        aws:
          rootVolume:
            iops: 2000
            size: 100
            type: io1
          type: m5.xlarge
    networking:
      networkType: OVNKubernetes
      clusterNetwork:
      - cidr: {{.Values.clusterNetworkCIDR }}
        hostPrefix: 23
      machineNetwork:
      - cidr: {{ .Values.machineNetworkCIDR }}
      serviceNetwork:
      - {{ .Values.serviceNetworkCIDR }}
    platform:
      aws:
        region: {{ .Values.region }}
    pullSecret: "" # skip, hive will inject based on it's secrets
    sshKey: |-
        ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCWVnOEYFaN6tp/CXn5aBgD5YZbbwJHhUYbAahoGz3IbP8YZZwyBvJvgy9CujKTaIpZHweYRwMEtvPaX65g8AQDd8t6Gqc+JVJue6HTqrawH2wvq8Qdhip9L09fK2WqtP7UbVF+fgiwm9kebajkAqtlOttcdHipeRy5TGVE2hbV1zqc6UjTo6lKzxflm2Jd5EMc4TZCleSFApBod+jgFZoke/8Q/GHWyQs7YaoE3h/JND7z6aye5HoAPQBT18y/4Amwj7h2hIcIsSJ8JAHsOZ0NB4gz1qwpkG/dYAYV1iARM/+qnZ7EJAt4DofqUAS1/0BdXK+1RL8uI0db4r8U3pTe+oFGORQHRNa+ehDoX1PdOU+o59OmjEaJpcq0YRB3NqOwfZzATUfOqcZswH0xC6WKi/UknBFPgJv6JfD0+dee/kWTmgFrzT6Ie9hRql2bA+qjSoPfWzPk+Gv1Wuf6UGdC2DpKPO+vOhVzRtog/cvwjGSJv5p2X6biRGiYy8a0bX0= rspazzol@rspazzol