apiVersion: hive.openshift.io/v1
kind: MachinePool
metadata:
  name: {{ .Release.Name }}-worker
  labels:
    {{- include "aws-cluster.labels" . | nindent 4 }}
spec:
  clusterDeploymentRef:
    name: '{{ .Release.Name }}'
  name: worker
  platform:
    aws:
      rootVolume:
        iops: 2000
        size: 100
        type: io1
      type: m5.xlarge
  replicas: {{ .Values.storageNodes.replicas }}
   