kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-patches-rbac
  labels:
    {{- include "aws-cluster.labels" . | nindent 4 }}  
subjects:
  - kind: ServiceAccount
    name: default
    namespace: {{ .Release.Name }} # namespace:operator
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io