apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-pull-secret
  labels:
    {{- include "aws-cluster.labels" . | nindent 4 }}
data:
  '.dockerconfigjson': eyJhdXRocyI6eyJub3RoaW5nLmNvbSI6eyJhdXRoIjoiWTJsaGJ3PT09PSIsImVtYWlsIjoiZmFrZUBjaWFvLmNvbSJ9fX0=
type: kubernetes.io/dockerconfigjson