apiVersion: apps.gitlab.com/v1beta1
kind: GitLab
metadata:
  name: gitlab
spec:
  chart:
    version: "8.1.1"
    values:
      certmanager:
        install: false
      prometheus:
        install: false
      global:
        hosts:
          domain: apps.${CLUSTER_BASE_DOMAIN}
        ingress:
          annotations:
            route.openshift.io/termination: edge
          class: none
          configureCertmanager: false
          tls:
            enabled: false
        appConfig:    
          omniauth:
            enabled: true
            #autoSignInWithProvider: openid_connect
            syncProfileFromProvider: ["openid_connect"]
            syncProfileAttributes: ['email']
            allowSingleSignOn: ["openid_connect"]
            blockAutoCreatedUsers: false
            autoLinkLdapUser: false
            autoLinkSamlUser: false
            autoLinkUser: ["openid_connect"]
            externalProviders: []
            allowBypassTwoFactor: ["openid_connect"]
            providers: 
            - secret: "oidc-keycloak"            
      nginx-ingress:
        enabled: false