apiVersion: tf.upbound.io/v1beta1
kind: Workspace
metadata:
  name: gitlab-configuration
spec:
  forProvider:
    module: |
      resource "gitlab_application" "devspaces-oidc" {
        confidential = true
        scopes       = ["api","write_repository","openid"]
        name         = "devspaces"
        redirect_url = "https://devspaces.apps.${CLUSTER_BASE_DOMAIN}/api/oauth/callback"
      }
    source: Inline
  publishConnectionDetailsTo:
    name: backstage-gitlab
    configRef:
      name: vault    