apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab-system
resources: 
- ./gitlab-root-secret.yaml
- ./gitlab.yaml
- ./link.yaml
- ./gitlab-configuration-workspace.yaml
- ./oidc-keycloak-secret.yaml
- ./patches-rbac.yaml
- ./patches.yaml
- ./root-pat-secret.yaml
- ./set-root-pat-job.yaml