kind: Secret
apiVersion: v1
metadata:
  name: root-pat
  annotations:
    reflector.v1.k8s.emberstack.com/reflection-allowed: "true"
    reflector.v1.k8s.emberstack.com/reflection-allowed-namespaces: "rhdh"
stringData:
  token: KbfdXFhoX407c0v5ZP2Y
type: Opaque