apiVersion: redhatcop.redhat.io/v1alpha1
kind: KubernetesAuthEngineRole
metadata:
  name: infra-secret-reader
  namespace: vault-admin
spec:
  authentication: 
    path: ${CLUSTER_NAME}
    role: vault-admin
  path: ${CLUSTER_NAME}
  policies:
    - infra-secret-reader
  targetNamespaces:
    targetNamespaceSelector:
      matchLabels:
        infra-secrets: "true"
  targetServiceAccounts:
  - "*"