apiVersion: redhatcop.redhat.io/v1alpha1
kind: VaultSecret
metadata:
  name: gitlab-credentials
spec:
  refreshThreshold: 85 # after 85% of the lease_duration of the dynamic secret has elapsed, refresh the secret
  vaultSecretDefinitions:
    - authentication:
        path: ${CLUSTER_NAME}
        role: secret-reader
        serviceAccount:
          name: default
      name: devspaces_oidc
      path: infra/clusters/${CLUSTER_NAME}/crossplane-secrets/devspaces-oidc
  output:
    name: gitlab-credentials
    stringData:
      id: '{{ .devspaces_oidc.application_id }}'
      sexret: '{{ .devspaces_oidc.secret }}'
    type: Opaque
    labels:
      app.kubernetes.io/part-of: che.eclipse.org
      app.kubernetes.io/component: oauth-scm-configuration
    annotations:
      che.eclipse.org/oauth-scm-server: gitlab
      che.eclipse.org/scm-server-endpoint: https://gitlab.apps.${CLUSTER_BASE_DOMAIN}/