apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: gitlab-system
resources: 
- ./namespace.yaml
- https://gitlab.com/api/v4/projects/18899486/packages/generic/gitlab-operator/1.1.1/gitlab-operator-openshift-1.1.1.yaml