kind: Secret
apiVersion: v1
metadata:
  name: keycloak-secrets
stringData:
  KEYCLOAK_BASE_URL: https://keycloak-sso.apps.${CLUSTER_BASE_DOMAIN}
  KEYCLOAK_REALM: myorg
  OIDC_METADATA_URL: https://keycloak-sso.apps.${CLUSTER_BASE_DOMAIN}/auth/realms/myorg/.well-known/openid-configuration
type: Opaque