apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rhdh

resources:
  - ./namespace.yaml
  - ./dynamic-plugins.yaml
  - ./rhdh-app-configmap.yaml
  - ./rhdh-secrets.yaml
  - ./rhdh.yaml
  - ./link.yaml
  - ./gitlab-secrets.yaml
  - ./kecloak-secrets.yaml
  - ./patches-rbac.yaml
  - ./patches.yaml