kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
data:
  app-config-rhdh.yaml: |
    signInPage: oidc 
    app:
      title: Red Hat Developer Hub
      baseUrl: https://backstage-developer-hub-rhdh.apps.${CLUSTER_BASE_DOMAIN}
    backend:
      auth:
        keys:
          - secret: ${BACKEND_SECRET}
      baseUrl: https://backstage-developer-hub-rhdh.apps.${CLUSTER_BASE_DOMAIN}
      cors:
        origin: https://backstage-developer-hub-rhdh.apps.${CLUSTER_BASE_DOMAIN} 
    auth:
      session:
        secret: ${SESSION_SECRET}
      environment: production
      providers:
        guest: null
        oidc:
          production:
            metadataUrl: ${OIDC_METADATA_URL}
            clientId: ${OIDC_CLIENT_ID}
            clientSecret: ${OIDC_CLIENT_SECRET}
            prompt: auto
            scope: 'openid profile email'
    integrations:
      gitlab:
        - host: gitlab.apps.${CLUSTER_BASE_DOMAIN}
          token: ${token}
          apiBaseUrl: https://gitlab.apps.${CLUSTER_BASE_DOMAIN}/api/v4
          baseUrl: https://gitlab.apps.${CLUSTER_BASE_DOMAIN}     
    catalog:
      rules:
        - allow: [Component, System, Group, Resource, Location, Template, API, User, Domain, Type]    
      providers:
        keycloakOrg:
          production:
            baseUrl: ${KEYCLOAK_BASE_URL}/auth
            loginRealm: ${KEYCLOAK_REALM}
            realm: ${KEYCLOAK_REALM}
            clientId: ${OIDC_CLIENT_ID}
            clientSecret: ${OIDC_CLIENT_SECRET}
            schedule:
              frequency: { seconds: 30 }
              timeout: { minutes: 3 }
              initialDelay: { seconds: 30 }
        gitlab:
          yourProviderId:
            host: gitlab.${CLUSTER_BASE_DOMAIN} # Identifies one of the hosts set up in the integrations
            apiBaseUrl: https://gitlab.${CLUSTER_BASE_DOMAIN}/api/v4
            branch: main # Optional. Used to discover on a specific branch
            fallbackBranch: main # Optional. Fallback to be used if there is no default branch configured at the Gitlab repository. It is only used, if `branch` is undefined. Uses `master` as default
            skipForkedRepos: false # Optional. If the project is a fork, skip repository
            entityFilename: catalog-info.yaml # Optional. Defaults to `catalog-info.yaml`
            projectPattern: '[\s\S]*' # Optional. Filters found projects based on provided patter. Defaults to `[\s\S]*`, which means to not filter anything
            schedule: # optional; same options as in TaskScheduleDefinition
              # supports cron, ISO duration, "human duration" as used in code
              frequency: { minutes: 1 }
              # supports ISO duration, "human duration" as used in code
              timeout: { minutes: 3 }                                                            
      