kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
data:
  app-config-rhdh.yaml: |
    signInPage: gitlab 
    app:
      title: Red Hat Developer Hub
      baseUrl: https://backstage-developer-hub-rhdh-gitlab.apps.${CLUSTER_BASE_DOMAIN}
    backend:
      auth:
        keys:
          - secret: ${BACKEND_SECRET}
      baseUrl: https://backstage-developer-hub-rhdh-gitlab.apps.${CLUSTER_BASE_DOMAIN}
      cors:
        origin: https://backstage-developer-hub-rhdh-gitlab.apps.${CLUSTER_BASE_DOMAIN} 
    auth:
      environment: development
      providers:
        gitlab:
          development:
            clientId: ${AUTH_GITLAB_CLIENT_ID}
            clientSecret: ${AUTH_GITLAB_CLIENT_SECRET}
            audience: https://gitlab.${CLUSTER_BASE_DOMAIN}
    integrations:
      gitlab:
        - host: gitlab.apps.${CLUSTER_BASE_DOMAIN}
          token: ${GITLAB_TOKEN}
          apiBaseUrl: https://gitlab.apps.${CLUSTER_BASE_DOMAIN}/api/v4
          baseUrl: https://gitlab.apps.${CLUSTER_BASE_DOMAIN}     
    catalog:
      rules:
        - allow: [Component, System, Group, Resource, Location, Template, API, User, Domain, Type]    
      providers:
        keycloakOrg:
          default:
            # ...
            # highlight-add-start
            schedule: # optional; same options as in TaskScheduleDefinition
              # supports cron, ISO duration, "human duration" as used in code
              frequency: { minutes: 1 }
              # supports ISO duration, "human duration" as used in code
              timeout: { minutes: 1 }
              initialDelay: { seconds: 15 }
              # highlight-add-end                                                
      