kind: ConfigMap
apiVersion: v1
metadata:
  name: app-config-rhdh
data:
  app-config-rhdh.yaml: |
    signInPage: oidc 
    app:
      title: Red Hat Developer Hub
      baseUrl: https://backstage-developer-hub-rhdh-gitlab.apps.${CLUSTER_BASE_DOMAIN}
    backend:
      auth:
        keys:
          - secret: ${BACKEND_SECRET}
      baseUrl: https://backstage-developer-hub-rhdh-gitlab.apps.${CLUSTER_BASE_DOMAIN}
      cors:
        origin: https://backstage-developer-hub-rhdh-gitlab.apps.${CLUSTER_BASE_DOMAIN} 
    auth:
      session:
        secret: ${SESSION_SECRET}
      environment: production
      providers:
        guest: null
        oidc:
          production:
            metadataUrl: ${OIDC_METADATA_URL}
            clientId: ${OIDC_CLIENT_ID}
            clientSecret: ${OIDC_CLIENT_SECRET}
            prompt: auto
            scope: 'openid profile email'
    integrations:
      gitlab:
        - host: gitlab.apps.${CLUSTER_BASE_DOMAIN}
          token: ${GITLAB_TOKEN}
          apiBaseUrl: https://gitlab.apps.${CLUSTER_BASE_DOMAIN}/api/v4
          baseUrl: https://gitlab.apps.${CLUSTER_BASE_DOMAIN}     
    catalog:
      rules:
        - allow: [Component, System, Group, Resource, Location, Template, API, User, Domain, Type]    
      providers:
        keycloakOrg:
          production:
            baseUrl: ${KEYCLOAK_BASE_URL}/auth
            loginRealm: ${KEYCLOAK_REALM}
            realm: ${KEYCLOAK_REALM}
            clientId: ${OIDC_CLIENT_ID}
            clientSecret: ${OIDC_CLIENT_SECRET}
            schedule:
              frequency: { seconds: 30 }
              timeout: { minutes: 3 }
              initialDelay: { seconds: 30 }                                              
      