---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: {{ include "quarkus-build.fullname" . }}
  labels:
    {{- include "quarkus-build.labels" . | nindent 4 }}
spec:
  params:
    - name: git-revision
      description: The git revision
      default: {{ .Values.git.branch }}
    - name: git-repo-url
      description: The repo url
    - name: output-image
      description: reference of the image that will get created
      default: {{ include "image.dev-url" . }}
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: {{ include "quarkus-build.fullname" . }}
        labels:
          backstage.io/kubernetes-id: {{ .Values.app.name }}
      spec:
        params:
          - name: source-repo
            value: $(tt.params.git-repo-url)
          - name: source-branch
            value: $(tt.params.git-revision)
          - name: output-image
            value: $(tt.params.output-image)
          - name: component-id
            value: {{ .Values.app.name }}
        pipelineRef:
          name: {{ include "quarkus-build.fullname" . }}
        serviceAccountName: pipeline
        timeout: 1h0m0s
        workspaces:
          - name: source-folder
            volumeClaimTemplate:
              spec:
                accessModes:
                  - ReadWriteOnce
                resources:
                  requests:
                    storage: 1Gi
          - emptyDir: {}
            name: maven-settings
          - name: docker-config
            secret:
              secretName: {{ .Values.app.name }}-registry-creds
