apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-options: ServerSideApply=true
spec:
  identityProviders:
  - name: htpasswd 
    mappingMethod: claim 
    type: HTPasswd
    htpasswd:
      fileData:
        name: htpass-secret  
  - name: oidckeycloak
    mappingMethod: claim
    type: OpenID
    openID:
      clientID: ocp-${CLUSTER_NAME}-client
      clientSecret: 
        name: oidc-secret
      extraScopes: []
      issuer: https://keycloak-sso.apps.${HUB_BASE_DOMAIN}/auth/realms/myorg
      claims:
        preferredUsername:
        - preferred_username
        name:
        - name
        email:
        - email
        groups:
        - groups