apiVersion: redhatcop.redhat.io/v1alpha1
kind: Patch
metadata:
  name: non-prod-patches
spec:
  serviceAccountRef:
    name: default
  patches:
    private-key:
      targetObjectRef:
        apiVersion: v1
        kind: Secret
        namespace: non-prod
        name: non-prod-ssh-private-key
      sourceObjectRefs:
      - apiVersion: v1
        kind: Secret
        namespace: open-cluster-management
        name: aws-credentials               
      patchTemplate: |
        data:
          ssh-privatekey: {{ (index (index . 1).data "ssh-privatekey") }}
      patchType: application/merge-patch+json   
    aws-credentials:
      targetObjectRef:
        apiVersion: v1
        kind: Secret
        namespace: non-prod
        name: non-prod-aws-creds
      sourceObjectRefs:
      - apiVersion: v1
        kind: Secret
        namespace: open-cluster-management
        name: aws-credentials               
      patchTemplate: |
        data:
          aws_access_key_id: {{ (index (index . 1).data "aws_access_key_id") }}
          aws_secret_access_key: {{ (index (index . 1).data "aws_secret_access_key") }}
      patchType: application/merge-patch+json   
    pull-secret-patch:
      targetObjectRef:
        apiVersion: v1
        kind: Secret
        namespace: non-prod
        name: non-prod-pull-secret
      sourceObjectRefs:
      - apiVersion: v1
        kind: Secret
        namespace: openshift-config
        name: pull-secret                
      patchTemplate: |
        data:
          .dockerconfigjson: {{ (index (index . 1).data ".dockerconfigjson") }}
      patchType: application/merge-patch+json
    # vault-registration-url-patch:
    #   targetObjectRef:
    #     apiVersion: redhatcop.redhat.io/v1alpha1
    #     kind: KubernetesAuthEngineConfig
    #     namespace: vault-admin
    #     name: non-prod
    #   sourceObjectRefs:
    #   - apiVersion: cluster.open-cluster-management.io/v1
    #     kind: ManagedCluster
    #     name: non-prod
    #   patchTemplate: |
    #     spec:
    #       kubernetesHost: {{ (index (index . 1).spec.managedClusterClientConfigs 0).url }}
    #   patchType: application/merge-patch+json      
